############# English navigation ##############

# main menu

[[main]]
name = "Projects"
url = "projects/"
weight = 1

[[main]]
name = "CV"
url = "cv/"
weight = 2




# footer menu

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3
